/**
 * Utility to convert the React QR Code SVG element into a high-res downloadable PNG.
 * 
 * @param {string} alias - The short alias of the link (used in filename).
 * @param {SVGSVGElement} svgElement - The SVG element generated by react-qr-code.
 * @returns {Promise<void>}
 */
export const downloadQrPng = (alias, svgElement) => {
  return new Promise((resolve, reject) => {
    try {
      if (!svgElement) {
        throw new Error("SVG element not found");
      }

      // 1. Serialize SVG element to XML string
      const serializer = new XMLSerializer();
      const svgString = serializer.serializeToString(svgElement);

      // 2. Build the data URL with SVG contents
      const svgBlob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' });
      const svgUrl = URL.createObjectURL(svgBlob);

      // 3. Load URL into virtual offscreen Image
      const img = new Image();
      img.onload = () => {
        try {
          // 4. Create standard high-res Canvas
          const canvas = document.createElement('canvas');
          const size = 1024; // High-res target
          canvas.width = size;
          canvas.height = size;
          const ctx = canvas.getContext('2d');

          // Fill background as white to support scanning on dark modes/contrast ratios
          ctx.fillStyle = '#ffffff';
          ctx.fillRect(0, 0, size, size);

          // Draw the loaded SVG image to canvas
          ctx.drawImage(img, 0, 0, size, size);

          // 5. Export canvas to PNG data URL
          const pngUrl = canvas.toDataURL('image/png');

          // 6. Trigger anchor download
          const downloadLink = document.createElement('a');
          downloadLink.href = pngUrl;
          downloadLink.download = `shortly-${alias}.png`;
          document.body.appendChild(downloadLink);
          downloadLink.click();
          document.body.removeChild(downloadLink);

          // Cleanup blob URL
          URL.revokeObjectURL(svgUrl);
          resolve();
        } catch (err) {
          URL.revokeObjectURL(svgUrl);
          reject(err);
        }
      };

      img.onerror = (err) => {
        URL.revokeObjectURL(svgUrl);
        reject(new Error("Failed to load QR image resource"));
      };

      img.src = svgUrl;
    } catch (err) {
      reject(err);
    }
  });
};
